### ISSUE TITLE
Empty trees should be represented by {} instead of null

### ISSUE THREAD

**Issue by DennisSchwartz** [repositive/query-parser#19]
We should move to use the empty object instead of null to represent an empty tree.

Here's a quick idea by @Istar-Eldritch on how to do that:

``` typescript
export interface Tree<O, T> {
  value: O;
  left: BTree<O, T> | T;
  right: BTree<O, T> | T;
}

type EmptyTree = {};
export type BTree<O, T> = EmptyTree | Tree<O, T>;
```

**Comment by Istar-Eldritch** [comment]
Closing this as no longer relevant. Empty trees are undefined.
